### ISSUE TITLE
Implement search user asset on landing page and fix copy to clipboard container

### ISSUE THREAD

**Issue by codeWhizperer** [Starknet-Africa-Edu/TBA-FRONTEND#46]
![landing](https://github.com/Starknet-Africa-Edu/TBA-FRONTEND/assets/63842643/edf0c1a3-d543-4e12-85a3-63436992b142)
![modal](https://github.com/Starknet-Africa-Edu/TBA-FRONTEND/assets/63842643/b1aa42ec-92c6-4dbe-8ea0-c17820db5069)

User should be able to search for asset  when an address is pasted in the search bar.

**Comment by stephanniegb** [comment]
I'd like to work on this

**Comment by Darlington02** [comment]
More context, we use Ark indexer for indexing NFTs on Starknet. You are expected to retrieve the address and using the Ark indexer, find the collection that matches that address. 

When a collection is found, should show up just below the search bar, which on click can take the user to a page where he sees all NFTs in that collection

<img width="698" alt="Screenshot 2024-02-21 at 14 08 32" src="https://github.com/Starknet-Africa-Edu/TBA-FRONTEND/assets/75126961/ecb04a01-1bef-4073-bd4a-541de660868c">

otherwise return "Collection not found"
